### ISSUE TITLE
Transformar e integrar os dados

### ISSUE THREAD

**Issue by jrsmarcilio** [AldenisFranca/dw_populacional#6]
- [x] Transformar e integrar os dados para que possa ser feita a carga dos dados nas tabelas destino
- [x] Carregar dos dados nas tabelas destino

<hr>

[Atividade dependente](https://github.com/AldenisFranca/dw_populacional/issues/5)

**Comment by AldenisFranca** [comment]
Atividade de transformação e carga completadas.
